config/routes.rb
Avalon::Application.routes.draw do
  root :to => 'home#home'
  
  # Directories
  get    '(/*path)/directories'     => 'directories#index'
  get    '(/*path)/directories/new' => 'directories#new'
  post   '(/*path)/directories'     => 'directories#create'
  get    '(/*path)/edit'            => 'directories#edit'
  put    '/*path'                   => 'directories#update'
  delete '/*path'                   => 'directories#destroy'
  get    '*path'                    => 'directories#show'
end # routes

app/models/directory.rb
class Directory
  include Mongoid::Document
  
  field :title, :type => String
  field :slug,  :type => String
  field :path,  :type => String
  
  belongs_to :parent, :class_name => "Directory", :inverse_of => :children
  has_many :children, :class_name => "Directory", :inverse_of => :parent
  
  validates :title, :presence => true
  validates :slug,  :presence => true, :uniqueness => { :scope => :parent }
  
  before_validation do |record|
    self[:slug] = slugify(record.title)
    self[:path] = (parent ? parent.path : '') + "/#{self.slug}"
  end # before validation
  
private
  def slugify string
    string ? string.parameterize.gsub(/\s+/, '_') : nil
  end # method slugify
  
  private :path=, :slug=
end # model Directory

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
  # GET (/:path)
  def show
    @directory = find_directory params[:path]
    
    redirect_to :root if @directory.nil?
  end # action show
  
  # GET (/:path)/directories
  def index
    @directory = find_directory params[:path]
  end # action index
  
  # GET (/:path)/directories/new
  def new
    @parent    = find_directory params[:path]
    @directory = Directory.new  params[:directory]
  end # action new
  
  # POST (/:path)/directories
  def create
    @parent    = find_directory params[:path]
    @directory = Directory.new params[:directory]
    @directory.parent = @parent
    
    if @directory.save
      redirect_to @directory.path
    else
      render :new
    end # if-else
  end # action create
  
  # GET (/:path)/edit
  def edit
    @directory = find_directory params[:path]
  end # action edit
  
  # PUT /:path
  def update
    @directory = find_directory params[:path]
    logger.debug "path = #{params[:path]}, directory = #{@directory.inspect}"
    if @directory.update_attributes params[:directory]
      redirect_to @directory.path
    else
      render :edit
    end # if-else
  end # method update
  
  # DELETE /:path
  def destroy
    @directory = find_directory params[:path]
    @parent    = @directory.parent
    @directory.destroy
    
    redirect_to @parent ? @parent.path : :root
  end # method destroy
  
  def find_directory path
    return nil if path.nil?
    
    Directory.find_by :path => "/#{path}"
  rescue Mongoid::Errors::DocumentNotFound
    nil
  end # method find_directory
end # controller DirectoriesController

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    
  end # action home
end # controller HomeController

app/helpers/application_helper.rb
module ApplicationHelper
  def action_form_for record, action, options = {}, &proc
    class_name = record.class.name.underscore
    
    case action
    when :create
      options[:html] ||= {}
      options[:html][:class] ||= "new_#{class_name}"
      options[:html][:id]    ||= "new_#{class_name}_#{record.id}"
    when :update
      options[:html] ||= {}
      options[:html][:class] ||= "edit_#{class_name}"
      options[:html][:id]    ||= "edit_#{class_name}_#{record.id}"
    end # case
    
    form_for record, options, &proc
  end # method action_form_for
end # helper ApplicationHelper

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/directories/_fields.html.haml
-# app/views/directories/_form.html.haml

- directory ||= @directory

= fields_for directory do |form|
  %p
    = form.label :title
    = form.text_field :title

app/views/directories/edit.html.haml
-# app/views/directories/edit.html.haml

- directory ||= @directory

%section
  %h3 Edit Directory
  
  = action_form_for directory, :update, :url => "#{directory.path}" do |form|
    = render "fields"
    %p
      = form.submit "Update Directory"

app/views/directories/index.html.haml
-# app/views/directories/index.html.haml

- directory ||= @directory
- directory_path = (directory ? directory.path : '') + '/'

%section
  %h3= directory ? directory.title : "Root Directory"
  
  - unless directory.nil?
    %section
      %h5 Parent Directory

      - parent = directory.parent
      - if parent.nil?
        %p= link_to "Root Directory", "/directories"
      - else
        %p= link_to parent.title, "#{parent.path}/directories"
  
  %section
    %h5 Child Directories
    %p=link_to "Create Directory", "#{directory_path}directories/new"
  
    - children = directory.nil? ? Directory.where(:parent => nil) : directory.children
    - if children.empty?
      %p There are no child directories.
    - else
      %table
        %thead
          %tr
            %th Title
            %th &nbsp;
            %th &nbsp;
        %tbody
        - children.each do |child|
          %tr
            %td= link_to child.title, "#{child.path}/directories"
            %td= link_to "Update", "#{child.path}/edit",
              :class => "edit-directory-link",
              :id => "edit-directory-#{child.slug}-link"
            %td= link_to "Destroy", "#{child.path}",
              :method => :delete,
              :class => "destroy-directory-link",
              :id => "destroy-directory-#{child.slug}-link"

app/views/directories/new.html.haml
-# app/views/directories/new.html.haml

- parent    ||= @parent
- directory ||= @directory

- parent_path = parent ? parent.path : ''

%section
  %h3 New Directory
  
  = action_form_for directory, :create, :url => "#{parent_path}/directories" do |form|
    = render "fields"
    %p
      = form.submit "Create Directory"

app/views/directories/show.html.haml
-# app/views/directories/show.html.haml

%section
  %h1= @directory.title

app/views/home/home.html.haml
-# app/views/home.html.haml

/ %p Greetings, programs!

%h1 Alpha
%p There lies the port; the vessel puffs her sails; there gloom the dark ...
%h2 Beta
%p
  Come, my friends. 'tis not too late to seek a newer world. Push off, and
  sitting well in order smite the sounding furrows; for my purpose holds to
  sail beyond the sunset, and the baths of all the western stars, until I die.
  It may be the gulfs will wash us down; it may be we shall touch the Happy
  Isles, and see the great Achilles, whom we knew. Though much is taken, much
  abides; and though we are not now that strength that in old days moved Earth
  and Heaven, that which we are, we are: one equal temper of heroic hearts,
  made weak by time and fate, but strong in will - to strive, to seek, to find,
  and not to yield.
%h3 Gamma
%h4 Delta
%h5 Epsilon
%h6 Zeta

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Avalon CMS
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  
  %body
    / %header
    %header
      %h1 Avalon CMS
      %nav
        %ul
          %li= link_to 'Home', '/directories'
          %li Articles
          %li Projects
          %li Blog
          %li= link_to 'About', :root
    
    #content
      = yield
    
    %footer
      = yield :breadcrumbs
      %p Hic Iacet Arthurus, Rex Quondam, Rexque Futuris